### ISSUE TITLE
Unable to Clone Repo

### ISSUE THREAD

**Issue by jesskrich** [grabcode/react-native-web-starter#1]
Have permissions changed on this?

**Comment by grabcode** [comment]
Hey @jesskrich, as far as I know, there's no settings for me to prevent you from cloning this repo, as it is public. I reckon it is likely coming from the setup on your machine.

Could you share a screenshot of the git message? Are you using SSH or HTTPS? If you're using SSH, have you setup your SSH public key in [your github profile](https://github.com/settings/keys)?

**Comment by jesskrich** [comment]
Thanks for the response Alex! Human error on my part. I had tried this the other day without being too familiar with SSH keys and after getting a precautionary tale from my boss about npm worms, after downloading several different things, saw that I had a new SSH key added automatically to my account and deleted it. Able to access now. Thanks!

**Comment by grabcode** [comment]
All good then! Don't hesitate to reach out if you have issues.
