### ISSUE TITLE
How I should use custom fonts?

### ISSUE THREAD

**Issue by 6pm** [grabcode/react-native-web-starter#11]
Hello. I want to include in my app custom font. How best way to do this with your great starter kit? Thank you!

**Comment by faceyspacey** [comment]
add it to `/web/src/index.html` so your code looks like this:

```
<!DOCTYPE html>
<meta charset="utf-8">
<title>React Native for Web</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<div id="react-root"></div>
<script src="/bundle.js"></script>
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

```

then specify the font family property like this: `<Text style={{fontFamily: Montserrat}}>sexy</Text>`

and done.

**Comment by grabcode** [comment]
Thanks @faceyspacey. Great question @6pm, it's giving me the idea of a FAQ.
