### ISSUE TITLE
bundle.js is missing

### ISSUE THREAD

**Issue by AmrAbdulrahman** [grabcode/react-native-web-starter#2]
I followed all your steps, but bundle.js is missing and it returns 404 at the browser.
Any ideas?

**Comment by grabcode** [comment]
Strange indeed. Could you share what `npm run dev` gives you?

This is what I'm expecting you to get (my project is named "rn4web"):
![screen shot 2016-06-24 at 1 51 57 pm](https://cloud.githubusercontent.com/assets/1523620/16327498/e681845c-3a12-11e6-8dd0-5ccd2382b2c2.png)

**Comment by grabcode** [comment]
Nothing @AmrAbdulrahman ? I can close the issue?

**Comment by AmrAbdulrahman** [comment]
Thanks @grabcode, I figured out the problem, you can close it.
