### ISSUE TITLE
Cannot find module "react/lib/getNextDebugID"

### ISSUE THREAD

**Issue by alexandrbig** [grabcode/react-native-web-starter#26]
Hello. 
I cloned repo, did 'npm install' and ran 'npm run dev'.
`$ npm run dev

> rn-web@1.1.0 dev D:\work\react-native\react-native-web-starter
> webpack-dev-server --port 3000 --config web/webpack.config.dev.js --inline --hot --colors --quiet

http://localhost:3000/
webpack result is served from /
content is served from D:\work\react-native\react-native-web-starter\web\src
`
In browser:
```
Module not found: Error: Cannot resolve module 'react/lib/getNextDebugID' in D:\work\react-native\react-native-web-starter\node_modules\react-dom\lib
resolve module react/lib/getNextDebugID in D:\work\react-native\react-native-web-starter\node_modules\react-dom\lib
```

Please let me know if any information missing.
Thank you in advance.

**Comment by lowsky** [comment]
For me, a simple `yarn add react-dom` seemed to fix this issue :-)

**Comment by damiaozi** [comment]
I fix this issue:
1、rm -rf node_modules 
2、yarn install node_modules
3、npm run dev
well done!!hope can help other people

**Comment by chuyinweilai** [comment]
yes, run the `yarn add react-dom` after `npm install`

**Comment by SupriyaKalghatgi** [comment]
None of these solutions worked for me

**Comment by mikely-fernanda** [comment]
para mim tambem nao funcionou :/ :-1:

**Comment by maksimgm** [comment]
@alexandrbig were you able to find a fix for this. I'm getting a similar error with Jest test runner:

    Cannot find module 'react/lib/getNextDebugID' from 'instantiateReactComponent.js'

**Comment by alexandrbig** [comment]
> @alexandrbig were you able to find a fix for this. I'm getting a similar error with Jest test runner:
> 
> ```
> Cannot find module 'react/lib/getNextDebugID' from 'instantiateReactComponent.js'
> ```

The project I worken on was closed, so I had no opportunity to recheck it.
