### ISSUE TITLE
React Native Libraries

### ISSUE THREAD

**Issue by Dylanb-dev** [grabcode/react-native-web-starter#3]
Hi,

You mentioned in your presentation that react native libraries could be used to some degree with this project, in particular material design libraries.

I tried to use https://github.com/xinthink/react-native-material-kit but kept getting an error, any ideas?

Thanks,
Dylan

**Comment by grabcode** [comment]
Hey @lolcookie,

There might be a confusion coming down from the term "libraries". If you refer to React Native extension aiming at bridging native capabilities to javascript, that will never work on RN4Web.

In a nutshell, any libraries that lean on ObjectiveC or Java code is deem to work exclusively on ReactNative. 

React-native-material-kit for instance is a bridge to expose "react-native-material-kit" pod to Javascript. That won't work in RN4Web. That being said, you may as well use a react material kit package, and build your own "React Native" component, wrapper whatever you get in Views. I suppose that would be hardly portable though to react-native as such package will certainly be tight to the DOM... 

Cheers,
Alex
